// ============================================
// BookVoyage - Books Database
// 100+ real books across 12 categories
// ============================================

const BOOKS_DATA = [

  // ===== FICTION (10) =====
  {id:1, title:"The Midnight Library", author:"Matt Haig", category:"Fiction", pages:304, year:2020, language:"English", format:"eBook, Audio", isbn:"978-0525559474", publisher:"Viking", rating:4.8, reviews:2348, reads:"12.5K", badge:"Bestseller", gradient:["#667eea","#764ba2"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780525559474-L.jpg", description:"Between life and death there is a library. When Nora Seed finds herself in the Midnight Library, she has a chance to try out every life she could have lived."},
  {id:2, title:"Where the Crawdads Sing", author:"Delia Owens", category:"Fiction", pages:384, year:2018, language:"English", format:"eBook, Audio", isbn:"978-0735219090", publisher:"G.P. Putnam's Sons", rating:4.6, reviews:3120, reads:"18.2K", badge:"Popular", gradient:["#a18cd1","#fbc2eb"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780735219090-L.jpg", description:"A coming-of-age mystery set in the marshlands of North Carolina, following the story of Kya Clark, the 'Marsh Girl', who becomes a murder suspect."},
  {id:3, title:"The Great Gatsby", author:"F. Scott Fitzgerald", category:"Fiction", pages:180, year:1925, language:"English", format:"eBook, PDF", isbn:"978-0743273565", publisher:"Scribner", rating:4.4, reviews:5840, reads:"25.1K", badge:"", gradient:["#f5af19","#f12711"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg", description:"Set in the Jazz Age, this classic novel explores themes of wealth, love, and the American Dream through the eyes of narrator Nick Carraway and the mysterious Jay Gatsby."},
  {id:4, title:"To Kill a Mockingbird", author:"Harper Lee", category:"Fiction", pages:336, year:1960, language:"English", format:"eBook, Audio, PDF", isbn:"978-0061120084", publisher:"Harper Perennial", rating:4.8, reviews:6210, reads:"30.8K", badge:"Bestseller", gradient:["#0f3460","#533483"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg", description:"A landmark of American literature about racial injustice in the Deep South, seen through the eyes of young Scout Finch as her father defends a wrongly accused Black man."},
  {id:5, title:"1984", author:"George Orwell", category:"Fiction", pages:328, year:1949, language:"English", format:"eBook, PDF", isbn:"978-0451524935", publisher:"Signet Classic", rating:4.7, reviews:4580, reads:"22.3K", badge:"Popular", gradient:["#2c3e50","#4ca1af"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg", description:"A dystopian masterpiece set in a totalitarian society under the watchful eye of Big Brother, exploring themes of surveillance, propaganda, and the power of language."},
  {id:6, title:"The Alchemist", author:"Paulo Coelho", category:"Fiction", pages:197, year:1988, language:"English", format:"eBook, Audio", isbn:"978-0062315007", publisher:"HarperOne", rating:4.5, reviews:3890, reads:"19.7K", badge:"Trending", gradient:["#f89820","#e76f00"], emoji:"&#128216;", cover:"https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg", description:"A philosophical novel about Santiago, an Andalusian shepherd boy who dreams of finding a worldly treasure and embarks on a journey of self-discovery."},
  {id:7, title:"Normal People", author:"Sally Rooney", category:"Fiction", pages:273, year:2018, language:"English", format:"eBook, Audio", isbn:"978-1984822178", publisher:"Hogarth Press", rating:4.3, reviews:1920, reads:"9.8K", badge:"", gradient:["#ee9ca7","#ffdde1"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9781984822178-L.jpg", description:"An intimate story of the complex relationship between Connell and Marianne from their school days in a small Irish town through their years at Trinity College Dublin."},
  {id:8, title:"The Kite Runner", author:"Khaled Hosseini", category:"Fiction", pages:371, year:2003, language:"English", format:"eBook, Audio, PDF", isbn:"978-1594631931", publisher:"Riverhead Books", rating:4.7, reviews:2760, reads:"15.3K", badge:"", gradient:["#c0392b","#e94560"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg", description:"A powerful story of friendship, betrayal, and redemption set against the backdrop of a changing Afghanistan, from the final days of the monarchy to the Taliban regime."},
  {id:9, title:"Pride and Prejudice", author:"Jane Austen", category:"Fiction", pages:279, year:1813, language:"English", format:"eBook, PDF", isbn:"978-0141439518", publisher:"Penguin Classics", rating:4.7, reviews:4120, reads:"20.5K", badge:"", gradient:["#c471f5","#fa71cd"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg", description:"One of the most beloved novels in English literature, following Elizabeth Bennet as she navigates manners, morality, and matrimony in Georgian England."},
  {id:10, title:"One Hundred Years of Solitude", author:"Gabriel García Márquez", category:"Fiction", pages:417, year:1967, language:"English", format:"eBook, Audio", isbn:"978-0060883287", publisher:"Harper Perennial", rating:4.6, reviews:2150, reads:"11.2K", badge:"", gradient:["#56ab2f","#a8e063"], emoji:"&#128215;", cover:"https://covers.openlibrary.org/b/isbn/9780060883287-L.jpg", description:"A landmark of magical realism that tells the multi-generational story of the Buendía family in the fictional town of Macondo, blending myth with reality."},

  // ===== SCIENCE (8) =====
  {id:11, title:"A Brief History of Time", author:"Stephen Hawking", category:"Science", pages:256, year:1988, language:"English", format:"eBook, Audio, PDF", isbn:"978-0553380163", publisher:"Bantam", rating:4.6, reviews:3480, reads:"25.1K", badge:"Bestseller", gradient:["#4facfe","#00f2fe"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780553380163-L.jpg", description:"Stephen Hawking explores the nature of time. From the Big Bang to black holes, this book makes complex physics accessible to the general reader."},
  {id:12, title:"Cosmos", author:"Carl Sagan", category:"Science", pages:396, year:1980, language:"English", format:"eBook, PDF", isbn:"978-0345539434", publisher:"Ballantine Books", rating:4.7, reviews:2890, reads:"18.4K", badge:"Popular", gradient:["#0c3483","#a2b6df"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780345539434-L.jpg", description:"Carl Sagan takes readers on an awe-inspiring journey through 15 billion years of cosmic evolution, exploring the intertwining of science and civilization."},
  {id:13, title:"The Gene: An Intimate History", author:"Siddhartha Mukherjee", category:"Science", pages:608, year:2016, language:"English", format:"eBook, Audio", isbn:"978-1476733524", publisher:"Scribner", rating:4.4, reviews:1560, reads:"8.9K", badge:"", gradient:["#11998e","#38ef7d"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9781476733524-L.jpg", description:"A riveting exploration of the gene and its central role in heredity, human development, and disease — from Mendel's pea garden to CRISPR gene editing."},
  {id:14, title:"Astrophysics for People in a Hurry", author:"Neil deGrasse Tyson", category:"Science", pages:224, year:2017, language:"English", format:"eBook, Audio", isbn:"978-0393609394", publisher:"W. W. Norton", rating:4.3, reviews:2210, reads:"14.2K", badge:"Trending", gradient:["#1a2a6c","#b21f1f"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9780393609394-L.jpg", description:"Neil deGrasse Tyson distills the cosmos into bite-sized pieces, covering everything from the Big Bang to dark energy in this concise and entertaining guide."},
  {id:15, title:"The Selfish Gene", author:"Richard Dawkins", category:"Science", pages:360, year:1976, language:"English", format:"eBook, PDF", isbn:"978-0198788607", publisher:"Oxford University Press", rating:4.5, reviews:1890, reads:"10.6K", badge:"", gradient:["#1e3c72","#2a5298"], emoji:"&#128216;", cover:"https://covers.openlibrary.org/b/isbn/9780198788607-L.jpg", description:"A groundbreaking work that reshaped the understanding of evolution by shifting the focus from organisms to genes as the fundamental units of natural selection."},
  {id:16, title:"Silent Spring", author:"Rachel Carson", category:"Science", pages:400, year:1962, language:"English", format:"eBook, PDF", isbn:"978-0618249060", publisher:"Houghton Mifflin", rating:4.4, reviews:1340, reads:"7.8K", badge:"", gradient:["#134e5e","#71b280"], emoji:"&#128215;", cover:"https://covers.openlibrary.org/b/isbn/9780618249060-L.jpg", description:"The book that launched the environmental movement, documenting the devastating effects of pesticides on ecosystems and calling for responsible stewardship of the Earth."},
  {id:17, title:"Sapiens: A Brief History of Humankind", author:"Yuval Noah Harari", category:"Science", pages:464, year:2011, language:"English", format:"eBook, Audio, PDF", isbn:"978-0062316097", publisher:"Harper Perennial", rating:4.5, reviews:4250, reads:"22.7K", badge:"Bestseller", gradient:["#3a1c71","#d76d77"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg", description:"A sweeping narrative of human history from the Stone Age to the Silicon Age, exploring how Homo sapiens came to dominate the Earth through cognitive, agricultural, and scientific revolutions."},
  {id:18, title:"The Origin of Species", author:"Charles Darwin", category:"Science", pages:703, year:1859, language:"English", format:"eBook, PDF", isbn:"978-0451529060", publisher:"Signet", rating:4.3, reviews:980, reads:"5.4K", badge:"", gradient:["#005c97","#363795"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780451529060-L.jpg", description:"Darwin's revolutionary work presenting the theory of evolution by natural selection, forever changing our understanding of the natural world and humanity's place in it."},

  // ===== TECHNOLOGY (8) =====
  {id:19, title:"Clean Code", author:"Robert C. Martin", category:"Technology", pages:464, year:2008, language:"English", format:"eBook, PDF", isbn:"978-0132350884", publisher:"Prentice Hall", rating:4.7, reviews:2670, reads:"15.3K", badge:"Bestseller", gradient:["#89f7fe","#66a6ff"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9780132350884-L.jpg", description:"A handbook of agile software craftsmanship that teaches developers how to write clean, maintainable code through principles, patterns, and practical case studies."},
  {id:20, title:"The Pragmatic Programmer", author:"David Thomas & Andrew Hunt", category:"Technology", pages:352, year:2019, language:"English", format:"eBook, PDF", isbn:"978-0135957059", publisher:"Addison-Wesley", rating:4.7, reviews:1980, reads:"11.7K", badge:"Popular", gradient:["#36d1dc","#5b86e5"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780135957059-L.jpg", description:"A timeless guide for software developers covering topics from personal responsibility and career development to architectural techniques for keeping code flexible."},
  {id:21, title:"Introduction to Algorithms", author:"Thomas H. Cormen", category:"Technology", pages:1312, year:2009, language:"English", format:"eBook, PDF", isbn:"978-0262033848", publisher:"MIT Press", rating:4.3, reviews:1240, reads:"6.8K", badge:"", gradient:["#0f2027","#2c5364"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780262033848-L.jpg", description:"The definitive textbook on algorithms, widely used in universities worldwide. Covers a broad range of algorithms in depth with mathematical rigor and practical clarity."},
  {id:22, title:"Design Patterns", author:"Erich Gamma, Richard Helm, Ralph Johnson & John Vlissides", category:"Technology", pages:395, year:1994, language:"English", format:"eBook, PDF", isbn:"978-0201633610", publisher:"Addison-Wesley", rating:4.4, reviews:1560, reads:"8.2K", badge:"", gradient:["#2c3e50","#3498db"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780201633610-L.jpg", description:"The seminal book by the 'Gang of Four' that catalogs 23 classic software design patterns, providing reusable solutions to common object-oriented design problems."},
  {id:23, title:"Cracking the Coding Interview", author:"Gayle Laakmann McDowell", category:"Technology", pages:687, year:2015, language:"English", format:"eBook, PDF", isbn:"978-0984782857", publisher:"CareerCup", rating:4.6, reviews:3150, reads:"19.5K", badge:"Trending", gradient:["#43cea2","#185a9d"], emoji:"&#128216;", cover:"https://covers.openlibrary.org/b/isbn/9780984782857-L.jpg", description:"The most popular book for technical interview preparation, featuring 189 programming questions and solutions, plus strategies for approaching algorithm and system design problems."},
  {id:24, title:"You Don't Know JS: Scope & Closures", author:"Kyle Simpson", category:"Technology", pages:278, year:2014, language:"English", format:"eBook, PDF", isbn:"978-1491904244", publisher:"O'Reilly Media", rating:4.5, reviews:1120, reads:"7.1K", badge:"", gradient:["#00b4db","#0083b0"], emoji:"&#128215;", cover:"https://covers.openlibrary.org/b/isbn/9781491904244-L.jpg", description:"A deep dive into the core mechanisms of JavaScript, exploring scope, closures, and the 'this' keyword to help developers truly understand the language beyond surface level."},
  {id:25, title:"Artificial Intelligence: A Modern Approach", author:"Stuart Russell & Peter Norvig", category:"Technology", pages:1152, year:2020, language:"English", format:"eBook, PDF", isbn:"978-0134610993", publisher:"Pearson", rating:4.4, reviews:890, reads:"5.6K", badge:"New", gradient:["#0b486b","#f56217"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780134610993-L.jpg", description:"The definitive AI textbook covering intelligent agents, search, knowledge representation, machine learning, natural language processing, robotics, and the philosophy of AI."},
  {id:26, title:"The Art of Computer Programming", author:"Donald E. Knuth", category:"Technology", pages:672, year:1997, language:"English", format:"PDF", isbn:"978-0201896831", publisher:"Addison-Wesley", rating:4.6, reviews:680, reads:"3.9K", badge:"", gradient:["#1f4037","#99f2c8"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9780201896831-L.jpg", description:"A comprehensive monograph by the legendary Donald Knuth, considered one of the most influential works in computer science, covering fundamental algorithms and data structures."},

  // ===== HISTORY (8) =====
  {id:27, title:"Guns, Germs, and Steel", author:"Jared Diamond", category:"History", pages:528, year:1997, language:"English", format:"eBook, Audio, PDF", isbn:"978-0393354324", publisher:"W. W. Norton", rating:4.3, reviews:2780, reads:"14.6K", badge:"Popular", gradient:["#ffecd2","#fcb69f"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780393354324-L.jpg", description:"A Pulitzer Prize-winning exploration of why certain civilizations conquered others, arguing that geography and environment — not racial superiority — shaped the fate of societies."},
  {id:28, title:"A People's History of the United States", author:"Howard Zinn", category:"History", pages:729, year:1980, language:"English", format:"eBook, PDF", isbn:"978-0062397348", publisher:"Harper Perennial", rating:4.4, reviews:1950, reads:"10.8K", badge:"", gradient:["#c94b4b","#4b134f"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780062397348-L.jpg", description:"A radical retelling of American history from the perspective of marginalized groups — Indigenous peoples, enslaved Africans, women, laborers — challenging traditional narratives."},
  {id:29, title:"The Diary of a Young Girl", author:"Anne Frank", category:"History", pages:283, year:1947, language:"English", format:"eBook, Audio, PDF", isbn:"978-0553296983", publisher:"Bantam", rating:4.7, reviews:4580, reads:"24.3K", badge:"Bestseller", gradient:["#e6dada","#274046"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780553296983-L.jpg", description:"The deeply moving diary of a young Jewish girl hiding from the Nazis in Amsterdam during World War II, offering an intimate record of courage, hope, and the human spirit."},
  {id:30, title:"Genghis Khan and the Making of the Modern World", author:"Jack Weatherford", category:"History", pages:312, year:2004, language:"English", format:"eBook, Audio", isbn:"978-0609809648", publisher:"Crown", rating:4.5, reviews:1340, reads:"7.9K", badge:"", gradient:["#cc5333","#753a88"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9780609809648-L.jpg", description:"A revelatory account that reshapes the image of Genghis Khan from brutal conqueror to visionary leader, showing how the Mongol Empire connected and transformed the world."},
  {id:31, title:"The Art of War", author:"Sun Tzu", category:"History", pages:68, year:-500, language:"English", format:"eBook, PDF", isbn:"978-1599869773", publisher:"Chiron Academic Press", rating:4.3, reviews:3620, reads:"19.1K", badge:"", gradient:["#b92b27","#1565c0"], emoji:"&#128216;", cover:"https://covers.openlibrary.org/b/isbn/9781599869773-L.jpg", description:"The ancient Chinese military treatise that remains essential reading for strategists, business leaders, and anyone navigating competitive environments."},
  {id:32, title:"Homo Deus: A Brief History of Tomorrow", author:"Yuval Noah Harari", category:"History", pages:464, year:2015, language:"English", format:"eBook, Audio", isbn:"978-0062464347", publisher:"Harper Perennial", rating:4.4, reviews:2080, reads:"12.4K", badge:"Trending", gradient:["#642b73","#c6426e"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780062464347-L.jpg", description:"Harari examines what might happen when old myths are coupled with godlike technologies like AI and genetic engineering, exploring humanity's possible futures."},
  {id:33, title:"The Silk Roads: A New History of the World", author:"Peter Frankopan", category:"History", pages:636, year:2015, language:"English", format:"eBook, Audio, PDF", isbn:"978-1101912379", publisher:"Vintage", rating:4.4, reviews:1560, reads:"8.7K", badge:"", gradient:["#f7971e","#ffd200"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9781101912379-L.jpg", description:"A bold rewriting of world history that places the ancient trade routes of Central Asia at the center of human civilization, from antiquity to the modern era."},
  {id:34, title:"Team of Rivals", author:"Doris Kearns Goodwin", category:"History", pages:944, year:2005, language:"English", format:"eBook, Audio, PDF", isbn:"978-0743270755", publisher:"Simon & Schuster", rating:4.6, reviews:1780, reads:"9.5K", badge:"", gradient:["#8e9eab","#eef2f3"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780743270755-L.jpg", description:"The political genius of Abraham Lincoln revealed through his relationships with the three men he defeated for the 1860 Republican nomination, then appointed to his Cabinet."},

  // ===== ROMANCE (8) =====
  {id:35, title:"It Ends with Us", author:"Colleen Hoover", category:"Romance", pages:385, year:2016, language:"English", format:"eBook, Audio", isbn:"978-1501110368", publisher:"Atria Books", rating:4.6, reviews:5120, reads:"28.4K", badge:"Bestseller", gradient:["#f093fb","#f5576c"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9781501110368-L.jpg", description:"A brave and heartbreaking novel that explores the painful reality of domestic violence through Lily, a woman caught between her first love and a manipulative husband."},
  {id:36, title:"The Notebook", author:"Nicholas Sparks", category:"Romance", pages:214, year:1996, language:"English", format:"eBook, Audio, PDF", isbn:"978-1455582877", publisher:"Grand Central", rating:4.4, reviews:3890, reads:"20.6K", badge:"Popular", gradient:["#ff9a9e","#fecfef"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9781455582877-L.jpg", description:"A timeless love story about Noah and Allie, whose youthful summer romance is rekindled years later, proving that true love endures against all odds."},
  {id:37, title:"Outlander", author:"Diana Gabaldon", category:"Romance", pages:850, year:1991, language:"English", format:"eBook, Audio", isbn:"978-0440212560", publisher:"Dell", rating:4.5, reviews:2670, reads:"15.8K", badge:"", gradient:["#c471f5","#fa71cd"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780440212560-L.jpg", description:"A sweeping historical romance in which Claire Randall, a WWII nurse, is mysteriously transported back to 18th-century Scotland, where she meets the dashing Jamie Fraser."},
  {id:38, title:"Me Before You", author:"Jojo Moyes", category:"Romance", pages:369, year:2012, language:"English", format:"eBook, Audio", isbn:"978-0143124542", publisher:"Penguin Books", rating:4.5, reviews:3240, reads:"17.2K", badge:"", gradient:["#f5576c","#ff6b6b"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780143124542-L.jpg", description:"The story of Louisa Clark, an ordinary girl who takes a job caring for Will Traynor, a wealthy young man left paralyzed, and the profound bond that develops between them."},
  {id:39, title:"The Time Traveler's Wife", author:"Audrey Niffenegger", category:"Romance", pages:546, year:2003, language:"English", format:"eBook, Audio, PDF", isbn:"978-0156029438", publisher:"Harvest Books", rating:4.3, reviews:2180, reads:"12.1K", badge:"", gradient:["#ee9ca7","#ffdde1"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780156029438-L.jpg", description:"An unconventional love story about Henry, who has a genetic disorder that causes him to time travel unpredictably, and Clare, the woman who loves him across time."},
  {id:40, title:"Beach Read", author:"Emily Henry", category:"Romance", pages:361, year:2020, language:"English", format:"eBook, Audio", isbn:"978-1984806734", publisher:"Berkley", rating:4.2, reviews:1890, reads:"10.5K", badge:"New", gradient:["#fbc2eb","#a6c1ee"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9781984806734-L.jpg", description:"Two writers with opposite genres — one romance, one literary fiction — swap styles for the summer in neighboring beach houses, finding love in the process."},
  {id:41, title:"People We Meet on Vacation", author:"Emily Henry", category:"Romance", pages:364, year:2021, language:"English", format:"eBook, Audio", isbn:"978-1984806758", publisher:"Berkley", rating:4.3, reviews:2340, reads:"13.7K", badge:"Trending", gradient:["#f78ca0","#f9748f"], emoji:"&#128216;", cover:"https://covers.openlibrary.org/b/isbn/9781984806758-L.jpg", description:"Best friends Alex and Poppy take annual summer vacations together, until a falling out. Two years later, Poppy plans one more trip to fix everything."},
  {id:42, title:"The Love Hypothesis", author:"Ali Hazelwood", category:"Romance", pages:384, year:2021, language:"English", format:"eBook, Audio", isbn:"978-0593336823", publisher:"Berkley", rating:4.2, reviews:2560, reads:"14.8K", badge:"New", gradient:["#e8cbc0","#636fa4"], emoji:"&#128215;", cover:"https://covers.openlibrary.org/b/isbn/9780593336823-L.jpg", description:"When PhD candidate Olive kisses a brooding professor to convince her best friend she's dating, a fake relationship spirals into something unexpectedly real."},

  // ===== CHILDREN (8) =====
  {id:43, title:"Harry Potter and the Sorcerer's Stone", author:"J.K. Rowling", category:"Children", pages:309, year:1997, language:"English", format:"eBook, Audio, PDF", isbn:"978-0590353427", publisher:"Scholastic", rating:4.8, reviews:8920, reads:"45.6K", badge:"Bestseller", gradient:["#d4fc79","#96e6a1"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780590353427-L.jpg", description:"The book that launched a global phenomenon, following orphan Harry Potter as he discovers he's a wizard and begins his first year at Hogwarts School of Witchcraft and Wizardry."},
  {id:44, title:"Charlotte's Web", author:"E.B. White", category:"Children", pages:184, year:1952, language:"English", format:"eBook, Audio, PDF", isbn:"978-0061124952", publisher:"HarperCollins", rating:4.7, reviews:3450, reads:"22.8K", badge:"Popular", gradient:["#a8e063","#56ab2f"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780061124952-L.jpg", description:"The classic tale of friendship between Wilbur the pig and Charlotte the spider, who saves his life by weaving words into her web — a story of loyalty and the beauty of life."},
  {id:45, title:"The Very Hungry Caterpillar", author:"Eric Carle", category:"Children", pages:26, year:1969, language:"English", format:"eBook, PDF", isbn:"978-0399226908", publisher:"Philomel Books", rating:4.8, reviews:4120, reads:"28.9K", badge:"", gradient:["#f7971e","#ffd200"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780399226908-L.jpg", description:"A beloved picture book following a caterpillar's journey through various foods before transforming into a beautiful butterfly, teaching counting, days of the week, and healthy eating."},
  {id:46, title:"Matilda", author:"Roald Dahl", category:"Children", pages:240, year:1988, language:"English", format:"eBook, Audio", isbn:"978-0142410370", publisher:"Puffin Books", rating:4.7, reviews:2890, reads:"18.4K", badge:"", gradient:["#11998e","#38ef7d"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9780142410370-L.jpg", description:"The story of an extraordinarily gifted little girl with neglectful parents and a terrifying headmistress, who discovers she has telekinetic powers."},
  {id:47, title:"The Cat in the Hat", author:"Dr. Seuss", category:"Children", pages:61, year:1957, language:"English", format:"eBook, PDF", isbn:"978-0394800011", publisher:"Random House", rating:4.6, reviews:3780, reads:"25.3K", badge:"", gradient:["#fc4a1a","#f7b733"], emoji:"&#128216;", cover:"https://covers.openlibrary.org/b/isbn/9780394800011-L.jpg", description:"A mischievous cat in a tall striped hat visits two bored children on a rainy day and turns their house upside down in this iconic beginner reader."},
  {id:48, title:"Wonder", author:"R.J. Palacio", category:"Children", pages:315, year:2012, language:"English", format:"eBook, Audio", isbn:"978-0375869020", publisher:"Knopf", rating:4.7, reviews:3560, reads:"21.6K", badge:"Trending", gradient:["#e1eec3","#f05053"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780375869020-L.jpg", description:"August Pullman was born with a facial difference. Starting 5th grade at a new school, Auggie wants to be treated as an ordinary kid — but his classmates can't get past his face."},
  {id:49, title:"Percy Jackson & the Lightning Thief", author:"Rick Riordan", category:"Children", pages:377, year:2005, language:"English", format:"eBook, Audio", isbn:"978-0786838653", publisher:"Disney Hyperion", rating:4.6, reviews:4230, reads:"24.1K", badge:"Popular", gradient:["#2193b0","#6dd5ed"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780786838653-L.jpg", description:"Twelve-year-old Percy Jackson discovers he's the son of Poseidon and is thrust into a quest to prevent a war among the Greek gods in this action-packed adventure."},
  {id:50, title:"Diary of a Wimpy Kid", author:"Jeff Kinney", category:"Children", pages:217, year:2007, language:"English", format:"eBook, PDF", isbn:"978-0810993136", publisher:"Amulet Books", rating:4.4, reviews:3120, reads:"19.7K", badge:"", gradient:["#c6ea8d","#fe90af"], emoji:"&#128215;", cover:"https://covers.openlibrary.org/b/isbn/9780810993136-L.jpg", description:"Greg Heffley's illustrated journal chronicles his misadventures navigating middle school, from avoiding bullies to surviving embarrassing family situations."},

  // ===== SELF-HELP (8) =====
  {id:51, title:"Atomic Habits", author:"James Clear", category:"Self-Help", pages:320, year:2018, language:"English", format:"eBook, Audio, PDF", isbn:"978-0735211292", publisher:"Avery", rating:4.8, reviews:6780, reads:"35.2K", badge:"Bestseller", gradient:["#667eea","#764ba2"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9780735211292-L.jpg", description:"A practical guide to building good habits and breaking bad ones, based on the science of tiny changes. Clear reveals how small, incremental improvements lead to remarkable results."},
  {id:52, title:"The 7 Habits of Highly Effective People", author:"Stephen R. Covey", category:"Self-Help", pages:381, year:1989, language:"English", format:"eBook, Audio, PDF", isbn:"978-1982137274", publisher:"Simon & Schuster", rating:4.6, reviews:4230, reads:"22.8K", badge:"Popular", gradient:["#4568dc","#b06ab3"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9781982137274-L.jpg", description:"Covey presents a holistic approach to personal and professional effectiveness through seven foundational habits — from being proactive to sharpening the saw."},
  {id:53, title:"Thinking, Fast and Slow", author:"Daniel Kahneman", category:"Self-Help", pages:499, year:2011, language:"English", format:"eBook, Audio, PDF", isbn:"978-0374533557", publisher:"Farrar, Straus and Giroux", rating:4.4, reviews:2890, reads:"16.4K", badge:"", gradient:["#6190e8","#a7bfe8"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780374533557-L.jpg", description:"Nobel laureate Kahneman explores the two systems that drive the way we think — the fast, intuitive System 1 and the slow, deliberate System 2 — and how they shape our judgments."},
  {id:54, title:"How to Win Friends and Influence People", author:"Dale Carnegie", category:"Self-Help", pages:288, year:1936, language:"English", format:"eBook, Audio, PDF", isbn:"978-0671027032", publisher:"Simon & Schuster", rating:4.7, reviews:5120, reads:"27.3K", badge:"Bestseller", gradient:["#f7971e","#ffd200"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780671027032-L.jpg", description:"The original and best self-help book on interpersonal skills, offering timeless advice on how to handle people, make them like you, and win them to your way of thinking."},
  {id:55, title:"The Power of Now", author:"Eckhart Tolle", category:"Self-Help", pages:236, year:1997, language:"English", format:"eBook, Audio", isbn:"978-1577314806", publisher:"New World Library", rating:4.5, reviews:2340, reads:"13.5K", badge:"", gradient:["#c471f5","#fa71cd"], emoji:"&#128216;", cover:"https://covers.openlibrary.org/b/isbn/9781577314806-L.jpg", description:"A spiritual guide to mindfulness and present-moment awareness, teaching readers how to quiet the mind, let go of pain, and find deep inner peace."},
  {id:56, title:"Mindset: The New Psychology of Success", author:"Carol S. Dweck", category:"Self-Help", pages:320, year:2006, language:"English", format:"eBook, Audio", isbn:"978-0345472328", publisher:"Ballantine Books", rating:4.4, reviews:1980, reads:"11.2K", badge:"", gradient:["#11998e","#38ef7d"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9780345472328-L.jpg", description:"Stanford psychologist Carol Dweck reveals how our beliefs about our abilities profoundly affect our lives: a 'fixed' vs. 'growth' mindset makes all the difference."},
  {id:57, title:"The Subtle Art of Not Giving a F*ck", author:"Mark Manson", category:"Self-Help", pages:224, year:2016, language:"English", format:"eBook, Audio", isbn:"978-0062457714", publisher:"Harper", rating:4.3, reviews:3560, reads:"19.8K", badge:"Trending", gradient:["#ff6a00","#ee0979"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780062457714-L.jpg", description:"A counterintuitive approach to living a good life that argues we should stop trying to be positive all the time and instead embrace our limitations honestly."},
  {id:58, title:"Deep Work", author:"Cal Newport", category:"Self-Help", pages:296, year:2016, language:"English", format:"eBook, Audio, PDF", isbn:"978-1455586691", publisher:"Grand Central", rating:4.5, reviews:1670, reads:"9.6K", badge:"", gradient:["#0575e6","#021b79"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9781455586691-L.jpg", description:"Cal Newport argues that the ability to perform deep, focused work is becoming increasingly rare and valuable, and provides rules for cultivating this crucial skill."},

  // ===== BIOGRAPHY (8) =====
  {id:59, title:"Steve Jobs", author:"Walter Isaacson", category:"Biography", pages:656, year:2011, language:"English", format:"eBook, Audio, PDF", isbn:"978-1451648539", publisher:"Simon & Schuster", rating:4.5, reviews:3120, reads:"17.8K", badge:"Popular", gradient:["#bdc3c7","#2c3e50"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9781451648539-L.jpg", description:"The definitive biography based on over 40 interviews with Steve Jobs, capturing the intensity and creative genius behind Apple, Pixar, and the digital revolution."},
  {id:60, title:"Becoming", author:"Michelle Obama", category:"Biography", pages:448, year:2018, language:"English", format:"eBook, Audio", isbn:"978-1524763138", publisher:"Crown", rating:4.7, reviews:4580, reads:"26.4K", badge:"Bestseller", gradient:["#c0392b","#e94560"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg", description:"Michelle Obama's deeply personal memoir traces her journey from the South Side of Chicago to the White House, reflecting on her experiences as First Lady and mother."},
  {id:61, title:"The Autobiography of Malcolm X", author:"Malcolm X & Alex Haley", category:"Biography", pages:500, year:1965, language:"English", format:"eBook, Audio, PDF", isbn:"978-0345350688", publisher:"Ballantine Books", rating:4.7, reviews:2340, reads:"14.2K", badge:"", gradient:["#1a1a2e","#e94560"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780345350688-L.jpg", description:"The classic autobiography of one of the most influential figures in American civil rights history, tracing Malcolm X's transformation from street hustler to international leader."},
  {id:62, title:"Long Walk to Freedom", author:"Nelson Mandela", category:"Biography", pages:656, year:1994, language:"English", format:"eBook, Audio, PDF", isbn:"978-0316548182", publisher:"Back Bay Books", rating:4.6, reviews:1890, reads:"10.8K", badge:"", gradient:["#0f3460","#16213e"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9780316548182-L.jpg", description:"Nelson Mandela's autobiography covering his early life, 27-year imprisonment, and his unwavering dedication to the fight against apartheid in South Africa."},
  {id:63, title:"Elon Musk", author:"Ashlee Vance", category:"Biography", pages:400, year:2015, language:"English", format:"eBook, Audio", isbn:"978-0062301239", publisher:"Ecco", rating:4.5, reviews:2560, reads:"14.6K", badge:"Trending", gradient:["#0c3483","#a2b6df"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780062301239-L.jpg", description:"The first major biography of one of the most daring entrepreneurs of our time, exploring Musk's ventures with SpaceX, Tesla, SolarCity, and his vision for humanity's future."},
  {id:64, title:"Einstein: His Life and Universe", author:"Walter Isaacson", category:"Biography", pages:704, year:2007, language:"English", format:"eBook, Audio, PDF", isbn:"978-0743264747", publisher:"Simon & Schuster", rating:4.4, reviews:1670, reads:"9.3K", badge:"", gradient:["#2c3e50","#4ca1af"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780743264747-L.jpg", description:"A vivid portrait of Albert Einstein as a rebel, genius, and humanist, showing how his scientific imagination sprang from his rebellious personality."},
  {id:65, title:"Educated", author:"Tara Westover", category:"Biography", pages:352, year:2018, language:"English", format:"eBook, Audio", isbn:"978-0399590504", publisher:"Random House", rating:4.7, reviews:3890, reads:"21.5K", badge:"Bestseller", gradient:["#f5af19","#f12711"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg", description:"A memoir about a woman who grows up in a survivalist family in Idaho, never attending school, yet ultimately earns a PhD from Cambridge University through sheer determination."},
  {id:66, title:"The Diary of Frida Kahlo", author:"Frida Kahlo", category:"Biography", pages:295, year:1995, language:"English", format:"eBook, PDF", isbn:"978-0810959545", publisher:"Abrams", rating:4.3, reviews:890, reads:"5.1K", badge:"", gradient:["#e94560","#533483"], emoji:"&#128216;", cover:"https://covers.openlibrary.org/b/isbn/9780810959545-L.jpg", description:"An intimate look at the legendary Mexican artist's life through her personal diary, filled with watercolor illustrations, thoughts on art, love, and pain."},

  // ===== MYSTERY & THRILLER (8) =====
  {id:67, title:"Gone Girl", author:"Gillian Flynn", category:"Mystery", pages:432, year:2012, language:"English", format:"eBook, Audio", isbn:"978-0307588371", publisher:"Crown", rating:4.3, reviews:4560, reads:"24.8K", badge:"Bestseller", gradient:["#1a1a2e","#16213e"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780307588371-L.jpg", description:"On their fifth wedding anniversary, Amy Dunne disappears. The police suspect her husband Nick. But is he really guilty? A twisting thriller about deception in modern marriage."},
  {id:68, title:"The Girl with the Dragon Tattoo", author:"Stieg Larsson", category:"Mystery", pages:672, year:2005, language:"English", format:"eBook, Audio, PDF", isbn:"978-0307454546", publisher:"Vintage", rating:4.4, reviews:3120, reads:"18.6K", badge:"Popular", gradient:["#0f2027","#203a43"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780307454546-L.jpg", description:"Journalist Mikael Blomkvist and hacker Lisbeth Salander team up to investigate a 40-year-old disappearance, uncovering dark secrets within one of Sweden's most powerful families."},
  {id:69, title:"The Da Vinci Code", author:"Dan Brown", category:"Mystery", pages:597, year:2003, language:"English", format:"eBook, Audio, PDF", isbn:"978-0307474278", publisher:"Anchor", rating:4.3, reviews:5230, reads:"32.1K", badge:"", gradient:["#2c3e50","#bdc3c7"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg", description:"A murder at the Louvre leads symbologist Robert Langdon and cryptographer Sophie Neveu on a breathless chase through codes and symbols to uncover a centuries-old religious mystery."},
  {id:70, title:"And Then There Were None", author:"Agatha Christie", category:"Mystery", pages:272, year:1939, language:"English", format:"eBook, Audio, PDF", isbn:"978-0062073488", publisher:"Harper", rating:4.7, reviews:4890, reads:"26.7K", badge:"Bestseller", gradient:["#141e30","#243b55"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9780062073488-L.jpg", description:"Ten strangers are lured to a remote island, where they are accused of past murders and begin dying one by one. Agatha Christie's masterpiece of mystery and suspense."},
  {id:71, title:"The Silent Patient", author:"Alex Michaelides", category:"Mystery", pages:325, year:2019, language:"English", format:"eBook, Audio", isbn:"978-1250301697", publisher:"Celadon Books", rating:4.5, reviews:3450, reads:"19.5K", badge:"Trending", gradient:["#0f0c29","#302b63"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg", description:"Alicia Berenson shoots her husband and then never speaks another word. Psychotherapist Theo Faber is determined to unravel the mystery of her silence."},
  {id:72, title:"In the Woods", author:"Tana French", category:"Mystery", pages:429, year:2007, language:"English", format:"eBook, Audio", isbn:"978-0143113492", publisher:"Penguin Books", rating:4.2, reviews:1560, reads:"8.4K", badge:"", gradient:["#232526","#414345"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780143113492-L.jpg", description:"Dublin detective Rob Ryan investigates the murder of a girl found at an archaeological dig in the woods where, as a boy, his two best friends vanished without a trace."},
  {id:73, title:"The Girl on the Train", author:"Paula Hawkins", category:"Mystery", pages:336, year:2015, language:"English", format:"eBook, Audio", isbn:"978-1594634024", publisher:"Riverhead Books", rating:4.1, reviews:3780, reads:"21.3K", badge:"", gradient:["#485563","#29323c"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9781594634024-L.jpg", description:"Rachel takes the same commuter train every morning, watching a seemingly perfect couple through the window — until she sees something shocking that draws her into their lives."},
  {id:74, title:"Sharp Objects", author:"Gillian Flynn", category:"Mystery", pages:254, year:2006, language:"English", format:"eBook, Audio", isbn:"978-0307341556", publisher:"Crown", rating:4.2, reviews:1890, reads:"10.2K", badge:"", gradient:["#1f1c2c","#928dab"], emoji:"&#128216;", cover:"https://covers.openlibrary.org/b/isbn/9780307341556-L.jpg", description:"Reporter Camille Preaker reluctantly returns to her hometown to cover a series of disturbing murders of young girls, confronting her own deeply troubled past."},

  // ===== NON-FICTION (8) =====
  {id:75, title:"Freakonomics", author:"Steven D. Levitt & Stephen J. Dubner", category:"Non-Fiction", pages:336, year:2005, language:"English", format:"eBook, Audio, PDF", isbn:"978-0060731335", publisher:"William Morrow", rating:4.3, reviews:2670, reads:"15.8K", badge:"Popular", gradient:["#ff9966","#ff5e62"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780060731335-L.jpg", description:"A rogue economist explores the hidden side of everything, revealing surprising connections between cheating teachers, sumo wrestlers, drug dealers, and real estate agents."},
  {id:76, title:"Outliers: The Story of Success", author:"Malcolm Gladwell", category:"Non-Fiction", pages:336, year:2008, language:"English", format:"eBook, Audio", isbn:"978-0316017930", publisher:"Back Bay Books", rating:4.4, reviews:3240, reads:"18.6K", badge:"Trending", gradient:["#f46b45","#eea849"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780316017930-L.jpg", description:"Gladwell examines what makes high-achievers different, arguing that success is not just about talent but about opportunity, cultural legacy, and the famous 10,000-hour rule."},
  {id:77, title:"The Immortal Life of Henrietta Lacks", author:"Rebecca Skloot", category:"Non-Fiction", pages:381, year:2010, language:"English", format:"eBook, Audio, PDF", isbn:"978-1400052189", publisher:"Broadway Books", rating:4.5, reviews:2120, reads:"12.4K", badge:"", gradient:["#e65c00","#f9d423"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9781400052189-L.jpg", description:"The story of Henrietta Lacks, whose cancer cells — taken without her knowledge — became the most important cells in medicine, raising questions about race, ethics, and science."},
  {id:78, title:"Quiet: The Power of Introverts", author:"Susan Cain", category:"Non-Fiction", pages:368, year:2012, language:"English", format:"eBook, Audio", isbn:"978-0307352156", publisher:"Crown", rating:4.4, reviews:2780, reads:"15.2K", badge:"", gradient:["#ff9a9e","#fad0c4"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9780307352156-L.jpg", description:"Susan Cain argues that introverts are dramatically undervalued in a culture that prizes extroversion, and shows how the quiet ones can harness their unique strengths."},
  {id:79, title:"Born a Crime", author:"Trevor Noah", category:"Non-Fiction", pages:304, year:2016, language:"English", format:"eBook, Audio", isbn:"978-0399588181", publisher:"Spiegel & Grau", rating:4.7, reviews:3890, reads:"21.7K", badge:"Bestseller", gradient:["#f7971e","#ffd200"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780399588181-L.jpg", description:"Trevor Noah's memoir of growing up mixed-race in South Africa during and after apartheid, where his very existence was literally a crime under the law."},
  {id:80, title:"In Cold Blood", author:"Truman Capote", category:"Non-Fiction", pages:343, year:1966, language:"English", format:"eBook, PDF", isbn:"978-0679745587", publisher:"Vintage", rating:4.4, reviews:1560, reads:"8.9K", badge:"", gradient:["#403b4a","#e7e9bb"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780679745587-L.jpg", description:"A pioneering work of literary nonfiction that reconstructs the 1959 murder of the Clutter family in Kansas and the investigation that led to the capture of the killers."},
  {id:81, title:"Between the World and Me", author:"Ta-Nehisi Coates", category:"Non-Fiction", pages:176, year:2015, language:"English", format:"eBook, Audio", isbn:"978-0451482211", publisher:"One World", rating:4.4, reviews:1890, reads:"10.5K", badge:"", gradient:["#373b44","#4286f4"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780451482211-L.jpg", description:"Written as a letter to his teenage son, Coates powerfully examines the reality of being Black in America, drawing from history, memoir, and unflinching observation."},
  {id:82, title:"The Year of Magical Thinking", author:"Joan Didion", category:"Non-Fiction", pages:227, year:2005, language:"English", format:"eBook, Audio, PDF", isbn:"978-1400078431", publisher:"Vintage", rating:4.2, reviews:1120, reads:"6.3K", badge:"", gradient:["#c9d6ff","#e2e2e2"], emoji:"&#128216;", cover:"https://covers.openlibrary.org/b/isbn/9781400078431-L.jpg", description:"Joan Didion's National Book Award-winning memoir about the year following her husband's sudden death, exploring grief, memory, and the stories we tell ourselves to survive."},

  // ===== POETRY (6) =====
  {id:83, title:"Milk and Honey", author:"Rupi Kaur", category:"Poetry", pages:208, year:2014, language:"English", format:"eBook, PDF", isbn:"978-1449474256", publisher:"Andrews McMeel", rating:4.3, reviews:3450, reads:"19.8K", badge:"Bestseller", gradient:["#e94560","#c0392b"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9781449474256-L.jpg", description:"A collection of poetry and prose about survival, divided into four chapters: the hurting, the loving, the breaking, and the healing. A #1 New York Times bestseller."},
  {id:84, title:"The Sun and Her Flowers", author:"Rupi Kaur", category:"Poetry", pages:256, year:2017, language:"English", format:"eBook, PDF", isbn:"978-1449486792", publisher:"Andrews McMeel", rating:4.2, reviews:2120, reads:"12.4K", badge:"", gradient:["#ff6b6b","#ffa07a"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9781449486792-L.jpg", description:"A journey of wilting, falling, rooting, rising, and blooming. Rupi Kaur's follow-up explores growth, ancestry, the honoring of one's roots, and the courage to uproot."},
  {id:85, title:"Leaves of Grass", author:"Walt Whitman", category:"Poetry", pages:152, year:1855, language:"English", format:"eBook, PDF", isbn:"978-0486456768", publisher:"Dover", rating:4.6, reviews:1340, reads:"8.1K", badge:"", gradient:["#56ab2f","#a8e063"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780486456768-L.jpg", description:"Whitman's groundbreaking collection of poems celebrating democracy, nature, love, and the human body, considered one of the most important works in American literature."},
  {id:86, title:"The Waste Land and Other Poems", author:"T.S. Eliot", category:"Poetry", pages:80, year:1922, language:"English", format:"eBook, PDF", isbn:"978-0156948777", publisher:"Harcourt", rating:4.4, reviews:890, reads:"4.6K", badge:"", gradient:["#8e0e00","#1f1c18"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9780156948777-L.jpg", description:"T.S. Eliot's modernist masterpiece, a complex poem reflecting the disillusionment of post-World War I society with its rich allusions and fragments of cultural history."},
  {id:87, title:"Selected Poems", author:"Emily Dickinson", category:"Poetry", pages:80, year:1890, language:"English", format:"eBook, PDF", isbn:"978-0486264660", publisher:"Dover", rating:4.6, reviews:780, reads:"4.2K", badge:"", gradient:["#c0392b","#8e44ad"], emoji:"&#128216;", cover:"https://covers.openlibrary.org/b/isbn/9780486264660-L.jpg", description:"A selection of Dickinson's enigmatic verses exploring death, immortality, nature, and the soul, written in her distinctive style of slant rhyme and unconventional punctuation."},
  {id:88, title:"Where the Sidewalk Ends", author:"Shel Silverstein", category:"Poetry", pages:176, year:1974, language:"English", format:"eBook, PDF", isbn:"978-0060256678", publisher:"Harper & Row", rating:4.8, reviews:2560, reads:"16.7K", badge:"Popular", gradient:["#f2994a","#f2c94c"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780060256678-L.jpg", description:"A beloved collection of playful, imaginative poems and drawings for children and adults alike, from the whimsical mind of Shel Silverstein."},

  // ===== BUSINESS (8) =====
  {id:89, title:"The Lean Startup", author:"Eric Ries", category:"Business", pages:336, year:2011, language:"English", format:"eBook, Audio, PDF", isbn:"978-0307887894", publisher:"Crown Business", rating:4.4, reviews:2340, reads:"13.5K", badge:"Popular", gradient:["#0f3460","#533483"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780307887894-L.jpg", description:"A new approach to business that's being adopted around the world, showing entrepreneurs how to build products customers actually want using continuous innovation."},
  {id:90, title:"Good to Great", author:"Jim Collins", category:"Business", pages:320, year:2001, language:"English", format:"eBook, Audio, PDF", isbn:"978-0066620992", publisher:"HarperBusiness", rating:4.5, reviews:1780, reads:"10.2K", badge:"", gradient:["#1e3c72","#2a5298"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780066620992-L.jpg", description:"Jim Collins examines why some companies make the leap from good to great while others don't, identifying key factors like Level 5 leadership and the Hedgehog Concept."},
  {id:91, title:"Zero to One", author:"Peter Thiel", category:"Business", pages:224, year:2014, language:"English", format:"eBook, Audio", isbn:"978-0804139298", publisher:"Crown Business", rating:4.5, reviews:2560, reads:"14.8K", badge:"Trending", gradient:["#4b6cb7","#182848"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780804139298-L.jpg", description:"PayPal co-founder Peter Thiel argues that the next generation of companies must innovate to create new things, not copy what already works. Every moment in business happens only once."},
  {id:92, title:"Think and Grow Rich", author:"Napoleon Hill", category:"Business", pages:238, year:1937, language:"English", format:"eBook, Audio, PDF", isbn:"978-1585424337", publisher:"TarcherPerigee", rating:4.6, reviews:4120, reads:"23.5K", badge:"Bestseller", gradient:["#c94b4b","#4b134f"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9781585424337-L.jpg", description:"The timeless bestseller based on Andrew Carnegie's success formula, distilling the wealth-building secrets of over 500 of America's most successful individuals."},
  {id:93, title:"Rich Dad Poor Dad", author:"Robert T. Kiyosaki", category:"Business", pages:336, year:1997, language:"English", format:"eBook, Audio, PDF", isbn:"978-1612681139", publisher:"Plata Publishing", rating:4.5, reviews:5670, reads:"31.2K", badge:"Bestseller", gradient:["#134e5e","#71b280"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9781612681139-L.jpg", description:"The #1 personal finance book of all time, contrasting the wealth-building approaches of 'Rich Dad' and 'Poor Dad' to challenge conventional wisdom about money and investing."},
  {id:94, title:"The 4-Hour Workweek", author:"Timothy Ferriss", category:"Business", pages:308, year:2007, language:"English", format:"eBook, Audio", isbn:"978-0307465351", publisher:"Harmony", rating:4.3, reviews:2120, reads:"12.1K", badge:"", gradient:["#36d1dc","#5b86e5"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780307465351-L.jpg", description:"Tim Ferriss shows how to escape the 9-5 grind, live anywhere, and join the 'New Rich' through lifestyle design, outsourcing, and mini-retirements."},
  {id:95, title:"Start with Why", author:"Simon Sinek", category:"Business", pages:256, year:2009, language:"English", format:"eBook, Audio", isbn:"978-1591846444", publisher:"Portfolio", rating:4.4, reviews:1890, reads:"10.8K", badge:"", gradient:["#005c97","#363795"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9781591846444-L.jpg", description:"Simon Sinek explores how great leaders inspire action by starting with 'why' — the purpose, cause, or belief that drives everything they do."},
  {id:96, title:"Principles: Life and Work", author:"Ray Dalio", category:"Business", pages:592, year:2017, language:"English", format:"eBook, Audio, PDF", isbn:"978-1501124020", publisher:"Simon & Schuster", rating:4.4, reviews:1560, reads:"8.9K", badge:"", gradient:["#2c3e50","#fd746c"], emoji:"&#128217;", cover:"https://covers.openlibrary.org/b/isbn/9781501124020-L.jpg", description:"Billionaire investor Ray Dalio shares the unconventional principles he developed over 40 years that helped him create unique results in both life and business."},

  // ===== BONUS: a few more to round out to 100 =====
  {id:97, title:"Dune", author:"Frank Herbert", category:"Fiction", pages:688, year:1965, language:"English", format:"eBook, Audio, PDF", isbn:"978-0441013593", publisher:"Ace", rating:4.6, reviews:3560, reads:"19.8K", badge:"Popular", gradient:["#f89820","#c0392b"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780441013593-L.jpg", description:"The epic science fiction saga of Paul Atreides on the desert planet Arrakis, exploring politics, religion, ecology, and the struggle for control of the most valuable substance in the universe: spice."},
  {id:98, title:"Brave New World", author:"Aldous Huxley", category:"Fiction", pages:311, year:1932, language:"English", format:"eBook, PDF", isbn:"978-0060850524", publisher:"Harper Perennial", rating:4.5, reviews:2340, reads:"13.6K", badge:"", gradient:["#485563","#29323c"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg", description:"A dystopian vision of a future society controlled through genetic engineering, conditioning, and a pleasure drug called soma, raising questions about freedom versus happiness."},
  {id:99, title:"Fahrenheit 451", author:"Ray Bradbury", category:"Fiction", pages:249, year:1953, language:"English", format:"eBook, Audio, PDF", isbn:"978-1451673319", publisher:"Simon & Schuster", rating:4.5, reviews:2780, reads:"15.4K", badge:"", gradient:["#e94560","#f39c12"], emoji:"&#128215;", cover:"https://covers.openlibrary.org/b/isbn/9781451673319-L.jpg", description:"In a future where books are banned and firemen burn them, Guy Montag begins to question everything he's been told — a prescient tale about censorship and the value of literature."},
  {id:100, title:"Project Hail Mary", author:"Andy Weir", category:"Fiction", pages:496, year:2021, language:"English", format:"eBook, Audio", isbn:"978-0593135204", publisher:"Ballantine Books", rating:4.8, reviews:4120, reads:"22.3K", badge:"New", gradient:["#d4fc79","#96e6a1"], emoji:"&#128213;", cover:"https://covers.openlibrary.org/b/isbn/9780593135204-L.jpg", description:"A lone astronaut wakes up on a spaceship with no memory and must save Earth from an extinction-level threat. A gripping sci-fi adventure from the author of The Martian."},
  {id:101, title:"The Master Algorithm", author:"Pedro Domingos", category:"Technology", pages:352, year:2015, language:"English", format:"eBook, PDF", isbn:"978-0465065707", publisher:"Basic Books", rating:4.3, reviews:1120, reads:"6.4K", badge:"", gradient:["#360033","#0b8793"], emoji:"&#128214;", cover:"https://covers.openlibrary.org/b/isbn/9780465065707-L.jpg", description:"The Master Algorithm explores how machine learning is remaking business, politics, and science — and what it means for the future of humanity."},
  {id:102, title:"The Hitchhiker's Guide to the Galaxy", author:"Douglas Adams", category:"Fiction", pages:224, year:1979, language:"English", format:"eBook, Audio, PDF", isbn:"978-0345391803", publisher:"Del Rey", rating:4.7, reviews:3890, reads:"21.4K", badge:"Popular", gradient:["#2193b0","#6dd5ed"], emoji:"&#128218;", cover:"https://covers.openlibrary.org/b/isbn/9780345391803-L.jpg", description:"When Earth is demolished to make way for a galactic highway, Arthur Dent hitches a ride on a passing spaceship, beginning the most absurd and hilarious adventure in science fiction."}
];

// Helper: get all unique categories with counts
function getCategoryCounts() {
  const counts = {};
  BOOKS_DATA.forEach(b => {
    counts[b.category] = (counts[b.category] || 0) + 1;
  });
  return counts;
}

// Helper: search books
function searchBooks(query, books) {
  if (!query) return books;
  const q = query.toLowerCase().trim();
  return books.filter(b =>
    b.title.toLowerCase().includes(q) ||
    b.author.toLowerCase().includes(q) ||
    b.isbn.includes(q) ||
    b.category.toLowerCase().includes(q) ||
    b.publisher.toLowerCase().includes(q)
  );
}

// Helper: filter books by category
function filterByCategory(category, books) {
  if (!category || category === 'all') return books;
  return books.filter(b => b.category === category);
}

// Helper: sort books
function sortBooks(books, sortBy) {
  const sorted = [...books];
  switch(sortBy) {
    case 'popular': sorted.sort((a,b) => parseFloat(b.reads) - parseFloat(a.reads)); break;
    case 'newest':  sorted.sort((a,b) => b.year - a.year); break;
    case 'az':      sorted.sort((a,b) => a.title.localeCompare(b.title)); break;
    case 'za':      sorted.sort((a,b) => b.title.localeCompare(a.title)); break;
    case 'rating':  sorted.sort((a,b) => b.rating - a.rating); break;
    default: break;
  }
  return sorted;
}

// Helper: generate book card HTML
function renderBookCard(book) {
  return `
    <div class="book-card">
      <a href="/book-detail/?id=${book.id}" class="book-cover-link" style="display:block;text-decoration:none;">
        <div class="book-cover" style="background: linear-gradient(135deg, ${book.gradient[0]}, ${book.gradient[1]});">
          ${book.badge ? '<span class="badge">' + book.badge + '</span>' : ''}
          <span class="rating">&#11088; ${book.rating}</span>
          <img src="${book.cover}" alt="${book.title}" loading="lazy" onerror="this.remove();">
        </div>
      </a>
      <div class="book-info">
        <span class="book-category">${book.category}</span>
        <h3><a href="/book-detail/?id=${book.id}" style="color:inherit;text-decoration:none;">${book.title}</a></h3>
        <p class="author">by ${book.author}</p>
        <div class="book-meta">
          <span><i class="fas fa-file-alt"></i> ${book.pages} pages</span>
          <span><i class="fas fa-eye"></i> ${book.reads} reads</span>
        </div>
      </div>
      <div class="book-actions">
        <a href="/book-detail/?id=${book.id}" class="btn btn-primary">Read Now</a>
      </div>
    </div>`;
}
